import { test, expect } from '@playwright/test'

test('analysis uses the same workflow layout as recap and exposes real artifacts in each step', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('http://127.0.0.1:8767/MoCoCo/#/examples/sintel-analysis')
  const nav = page.getByRole('navigation', { name: '制作流程' })
  await expect(nav.getByRole('link')).toHaveCount(7)
  await expect(page.getByRole('heading', { name: '原片与素材', exact: true })).toBeVisible()
  await page.locator('.shot-grid button').first().click()
  await expect(page.locator('.example-frame-large')).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await nav.getByRole('link', { name: '资料检索 · RAG' }).click()
  await expect(page.getByRole('heading', { name: '一次真实 RAG 运行记录' })).toBeVisible()
  await page.getByLabel('筛选摘记（关键词，不调用模型）').fill('不存在的关键词')
  await expect(page.getByRole('status')).toContainText('没有匹配的资料')
  await page.getByRole('button', { name: '表情', exact: true }).click()
  await expect(page.getByRole('heading', { name: /Open Source Goes to Hollywood/ })).toBeVisible()
  await page.getByText('展开检索依据', { exact: true }).first().click()
  await expect(page.locator('blockquote').first()).toContainText('Pant')
  await nav.getByRole('link', { name: '成片文案', exact: true }).click()
  await expect(page.locator('.example-script-paragraph')).toHaveCount(10)
  await page.getByText('查看本段资料依据', { exact: true }).nth(5).click()
  await expect(page.locator('.example-script-paragraph').nth(5)).toContainText('Shashwat Pant')
  await nav.getByRole('link', { name: '镜头与资料图', exact: true }).click()
  await expect(page.getByText('David Revoy / Blender Foundation', { exact: false })).toBeVisible()
  await page.screenshot({ path: '/tmp/sintel-workflow-shots.png', fullPage: false })
  await nav.getByRole('link', { name: '剪辑时间线', exact: true }).click()
  await expect(page.locator('.clip-strip')).toHaveCount(10)
  await expect(page.locator('.clip-block').first()).toContainText('成片')
  await nav.getByRole('link', { name: '配音与字幕', exact: true }).click()
  await expect(page.locator('.timing-table tbody tr')).toHaveCount(10)
  await page.getByText('展开完整字幕与时间码').click()
  await expect(page.locator('pre')).toContainText('她走过漫长的路')
  await expect.poll(() => page.locator('audio').evaluate((a: HTMLAudioElement) => a.duration), { timeout: 30000 }).toBeGreaterThan(260)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await nav.getByRole('link', { name: '剪辑时间线', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.reload()
  await expect(nav.getByRole('link', { name: '剪辑时间线', exact: true })).toHaveClass('active')
  await page.screenshot({ path: '/tmp/sintel-workflow-mobile.png', fullPage: false })
  await page.goto('http://127.0.0.1:8767/MoCoCo/#/examples/sherlock-jr')
  await expect(nav.getByRole('link')).toHaveCount(6)
  await nav.getByRole('link', { name: '文案', exact: true }).click()
  await expect(page.locator('.example-script-paragraph').first()).toBeVisible()
  await nav.getByRole('link', { name: '导出', exact: true }).click()
  await expect(page.locator('video')).toBeVisible()
  expect(errors).toEqual([])
})

test('local editor retrieves uploaded source evidence and reports a missing match', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('mococo.ui_lang', 'zh'))
  await page.goto('http://127.0.0.1:8766/p/sintel-rag/script')
  await expect(page.getByRole('heading', { name: '资料与论据 · RAG' })).toBeVisible()
  await page.getByLabel('希望补充哪一项论据？').fill('悲剧 表情')
  await page.getByRole('button', { name: '检索资料（不调用模型）' }).click()
  await expect(page.locator('blockquote').first()).toContainText('Pant')
  await page.getByLabel('希望补充哪一项论据？').fill('不存在的关键词')
  await page.getByRole('button', { name: '检索资料（不调用模型）' }).click()
  await expect(page.getByRole('status')).toContainText('未找到相关资料')
  await expect(page.getByRole('button', { name: '确认作为写作依据' }).first()).toBeEnabled()
  await page.screenshot({ path: '/tmp/mococo-rag-local.png', fullPage: true })
})


test('local editor shows an approved Commons insert on the timeline and exports its credits', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => localStorage.setItem('mococo.ui_lang', 'zh'))
  await page.goto('http://127.0.0.1:8766/p/sintel-rag/shots')
  await page.getByText('检索与插入外部图片', { exact: true }).click()
  await expect(page.getByRole('button', { name: '已插入 · 撤回', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '确认许可并插入本段', exact: true }).first()).toBeVisible()
  const portrait = page.locator('details img').nth(1)
  await expect.poll(() => portrait.evaluate((img: HTMLImageElement) => img.naturalWidth), { timeout: 15000 }).toBeGreaterThan(0)
  await page.screenshot({ path: '/tmp/mococo-rag-images.png', fullPage: true })
  await page.goto('http://127.0.0.1:8766/p/sintel-rag/cut')
  await expect(page.locator('.clip-block img')).toHaveCount(1)
  await expect(page.locator('.clip-block img')).toHaveAttribute('src', /commons-22488114/)
  const credits = await request.get('http://127.0.0.1:8766/api/projects/sintel-rag/image-credits')
  expect(credits.ok()).toBeTruthy()
  expect(await credits.text()).toContain('David Revoy / Blender Foundation')
  expect(errors).toEqual([])
})

test('finished Sintel commentary loads and chapter buttons seek the actual video', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('http://127.0.0.1:8767/MoCoCo/#/examples/sintel-analysis/export')
  const video = page.getByLabel('Sintel 深度解析成片')
  await expect(video).toBeVisible()
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.duration), { timeout: 60000 }).toBeGreaterThan(290)
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.videoWidth)).toBe(1280)
  await video.evaluate((v: HTMLVideoElement) => { v.muted = true })
  await page.getByRole('button', { name: /七｜设计资料能说明什么/ }).click()
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.currentTime), { timeout: 20000 }).toBeGreaterThan(189)
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.paused)).toBe(false)
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.readyState), { timeout: 20000 }).toBeGreaterThanOrEqual(2)
  await page.screenshot({ path: '/tmp/sintel-film-player.png', fullPage: false })
  await page.getByText('展开成片解说词', { exact: true }).click()
  await expect(page.getByText('她走过漫长的路，只想找回曾经救过的小龙。', { exact: false }).first()).toBeVisible()
})
