import { test, expect } from '@playwright/test'

test('public analysis filters real notes, shows recorded evidence and exports chosen interpretations', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('http://127.0.0.1:8767/MoCoCo/')
  await page.getByRole('link', { name: /Sintel · 从照料到悲剧/ }).click()
  await expect(page.getByRole('heading', { name: 'Sintel · 从照料到悲剧', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '一次真实 RAG 运行记录' })).toBeVisible()
  const filter = page.getByLabel('筛选摘记（关键词，不调用模型）')
  await filter.fill('不存在的关键词')
  await expect(page.getByRole('status')).toContainText('没有匹配的资料')
  await page.getByRole('button', { name: '表情', exact: true }).click()
  await expect(page.getByRole('heading', { name: /Open Source Goes to Hollywood/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Sharing/ })).toHaveCount(0)
  await page.getByText('展开检索依据', { exact: true }).first().click()
  await expect(page.locator('blockquote').first()).toContainText('s-e66e')
  await page.getByLabel('纳入我的草稿').first().check()
  await page.getByLabel('我的修改和需要补查的地方').fill('回看表情与配乐的关系，保留其他解释。')
  await page.getByLabel('在我的草稿中加入这张资料图').check()
  await expect(page.getByRole('status').last()).toContainText('插入计划')
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出选中论点、修改与来源' }).click()
  const download = await downloaded
  expect(download.suggestedFilename()).toBe('sintel-analysis-notes.md')
  const stream = await download.createReadStream()
  let text = ''
  for await (const bytes of stream!) text += bytes.toString()
  expect(text).toContain('回看表情与配乐')
  expect(text).toContain('https://www.opensourceforu.com/')
  expect(text).toContain('CC')
  expect(text).toContain('David Revoy / Blender Foundation')
  expect(text).toContain('Character_Sintel-portrait-young.png')
  await page.screenshot({ path: '/tmp/mococo-rag-public.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('local editor retrieves uploaded source evidence and reports a missing match', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('mococo.ui_lang', 'zh'))
  await page.goto('http://127.0.0.1:8766/p/sintel-rag/script')
  await expect(page.getByRole('heading', { name: '资料与论据 · RAG' })).toBeVisible()
  await page.getByLabel('希望补充哪一项论据？').fill('悲剧 表情')
  await page.getByRole('button', { name: '检索资料（不调用模型）' }).click()
  await expect(page.locator('blockquote').first()).toContainText('Pant')
  await page.getByLabel('希望补充哪一项论据？').fill('不存在的关键词')
  await page.getByRole('button', { name: '检索资料（不调用模型）' }).click()
  await expect(page.getByRole('status')).toContainText('未找到相关资料')
  await expect(page.getByRole('button', { name: '确认作为写作依据' }).first()).toBeEnabled()
  await page.screenshot({ path: '/tmp/mococo-rag-local.png', fullPage: true })
})


test('local editor shows an approved Commons insert on the timeline and exports its credits', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => localStorage.setItem('mococo.ui_lang', 'zh'))
  await page.goto('http://127.0.0.1:8766/p/sintel-rag/shots')
  await page.getByText('检索与插入外部图片', { exact: true }).click()
  await expect(page.getByRole('button', { name: '已插入 · 撤回', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '确认许可并插入本段', exact: true }).first()).toBeVisible()
  const portrait = page.locator('details img').nth(1)
  await expect.poll(() => portrait.evaluate((img: HTMLImageElement) => img.naturalWidth), { timeout: 15000 }).toBeGreaterThan(0)
  await page.screenshot({ path: '/tmp/mococo-rag-images.png', fullPage: true })
  await page.goto('http://127.0.0.1:8766/p/sintel-rag/cut')
  await expect(page.locator('.clip-block img')).toHaveCount(1)
  await expect(page.locator('.clip-block img')).toHaveAttribute('src', /commons-22488114/)
  const credits = await request.get('http://127.0.0.1:8766/api/projects/sintel-rag/image-credits')
  expect(credits.ok()).toBeTruthy()
  expect(await credits.text()).toContain('David Revoy / Blender Foundation')
  expect(errors).toEqual([])
})
